In [2]:
!pip install laspy

In [24]:
# read 3d models las files and print first 10 points along with the header
import numpy as np
import laspy
import sys

def read_las_file(file_name):
    try:
        las_file = laspy.read(file_name)
        print("-----------------------------file: ", file_name)

        print(las_file.header)
        print(las_file.header.scale)
        print(las_file.header.offset)
        print(las_file.header.min)
        print(las_file.header.max)
        print(las_file.header.point_count)
        print(las_file.header.x_scale)
        print(las_file.header.y_scale)
        print(las_file.header.z_scale)
        print(las_file.header.x_offset)
        print(las_file.header.y_offset)
        print(las_file.header.z_offset)
        print(las_file.header.x_max)
        print(las_file.header.y_max)
        print(las_file.header.z_max)
        print(las_file.header.x_min)
        print(las_file.header.y_min)
        print(las_file.header.z_min)
        # print(las_file.header.data_offset)
        print(las_file.header.vlrs)
        print(las_file.header.point_records_count)
        print(las_file.header.point_return_count)
        # print(las_file.header.classification)
        for i in range(10):
            print(las_file.x[i], las_file.y[i], las_file.z[i])
        print("-------------------------------------------------END")
    except Exception as e:
        print(e)
        sys.exit(1)

if __name__ == '__main__':
    lasfiles=["build/output_pointcloud_pila_original.las", "build/output_pointcloud_pila_shifted.las"]
    for file in lasfiles:
        read_las_file(file)


-----------------------------file:  build/output_pointcloud_pila_original.las
<LasHeader(1.3, <PointFormat(3, 0 bytes of extra dims)>)>
[0.001 0.001 0.001]
[ 369000. 5148000.       0.]
[3.69142281e+05 5.14848800e+06 5.50000793e+02]
[3.69144344e+05 5.14849150e+06 5.61660095e+02]
11272018
0.001
0.001
0.001
369000.0
5148000.0
0.0
369144.34375
5148491.5
561.6600952148438
369142.28125
5148488.0
550.0007934570312
[]
11272018
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
369143.25 5148489.0 552.432
369143.25 5148489.0 552.433
369143.25 5148489.0 552.437
369143.25 5148489.0 552.434
369143.25 5148489.0 552.439
369143.25 5148489.0 552.439
369143.25 5148489.0 552.441
369143.25 5148489.0 552.441
369143.25 5148489.0 552.445
369143.25 5148489.0 552.445
-------------------------------------------------END
-----------------------------file:  build/output_pointcloud_pila_shifted.las
<LasHeader(1.3, <PointFormat(3, 0 bytes of extra dims)>)>
[0.001 0.001 0.001]
[143.25337219 488.99816895 552.43255615]
[142.27539063 48